eshop/urls.py
from ast import Store
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls') ),
    path('accounts/',include('allauth.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import Brand_list, Index,Signup,Login, filter_data,logout,search,Brand_list,category,product_detail,add_to_cart,cart_list,delete_cart_item,update_cart_item,checkout,payment_done,payment_cancelled
urlpatterns = [
    path('',Index.as_view(),name='home'),
    path('signup',Signup.as_view(),name='signup'),
    path('product/<int:id>',product_detail,name='product-detail'),
    path('login',Login.as_view(),name='login'),
    path('logout',logout,name='logout'),
    path('search',search,name='search'),
    path('brand',Brand_list,name='brand'),
    path('category',category,name='category'),
    path('add-to-cart',add_to_cart,name='add_to_cart'),
    path('filter-data',filter_data,name='filter_data'),
    path('cart',cart_list,name='cart'),
    path('delete-from-cart',delete_cart_item,name='delete-from-cart'),
    path('update-to-cart',update_cart_item,name='update-to-cart'),
    path('checkout',checkout,name='checkout'),
     path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_cancelled, name='payment_cancelled'),




] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/models.py
from calendar import datetime
from distutils.command.upload import upload
from django.utils.html import mark_safe
from email.mime import image
from django.db import models
import datetime

# Create your models here.
class Product(models.Model):
    name=models.CharField(max_length=40)
    category=models.ForeignKey("Category",on_delete=models.CASCADE,default=1)
    description=models.TextField(max_length=200,default='',null=True,blank=True)
    slug=models.CharField(max_length=400)
    specs=models.TextField()
    brand=models.ForeignKey("Brand",on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    class Meta:
        verbose_name_plural='5. product '
    
    def __str__(self):
        return self.name

    @staticmethod
    def get__products_by_id(ids):
        return Product.objects.filter(id__in=ids)

    @staticmethod
    def get_all__products():
        return Product.objects.all()
    @staticmethod
    def get_all__products_by_ID(category_id):
        if category_id:
            return Product.objects.filter(category=category_id)
        else:
            return Product.get_all__products();
    @staticmethod
    def get_all__products_by_brandID(brand_id):
        if brand_id:
            return Product.objects.filter(brand=brand_id)
        else:
            return Product.get_all__products();

class Category(models.Model):
    name=models.CharField(max_length=20)
    image=models.ImageField(upload_to='uploads/cat/')
    class Meta:
        verbose_name_plural='1. categories '
    def __str__(self):
        return self.name
    @staticmethod
    def get_all__category():
        return Category.objects.all()

class Brand(models.Model):
    name=models.CharField(max_length=20)
    image=models.ImageField(upload_to='uploads/brand/')
    class Meta:
        verbose_name_plural='2. brand '
    def __str__(self):
        return self.name
    @staticmethod
    def get_all__brand():
        return Brand.objects.all()
class Color(models.Model):
    name=models.CharField(max_length=20)
    color_code=models.CharField(max_length=100)
    def color_bg(self):
        return mark_safe('<div style="width:30px; height:30px;background-color:%s"></div>' %(self.color_code))
    class Meta:
        verbose_name_plural='3. colors '
    def __str__(self):
        return self.name

class Size(models.Model):
    name=models.CharField(max_length=100)
    class Meta:
        verbose_name_plural='4. size '
    def __str__(self):
        return self.name

class Customer(models.Model):
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    phone=models.CharField(max_length=10)
    email=models.EmailField()
    password=models.CharField(max_length=500)
    class Meta:
        verbose_name_plural='7. customer '

    def register(self):
        self.save()

    @staticmethod
    def get_customer_by_email(email):
        try:
             return Customer.objects.get(email=email)
        except:
            return False
    def isExists(self):
        if Customer.objects.filter(email=self.email):
            return True
        else:
            return False

class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    price=models.IntegerField()
    address=models.CharField(max_length=50,default='',blank=True)
    phone=models.CharField(max_length=50,default='',blank=True)
    date=models.DateField(default=datetime.datetime.today)
    status=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='8. orders '
    def placeorder(self):
        self.save() 

    
    @staticmethod
    def get_order_by_customer(customer_id):
        return Order\
            .objects\
                .filter(customer=customer_id)\
                    .order_by('-date')

class ProductAttribute(models.Model):
    size=models.ForeignKey("Size",on_delete=models.CASCADE)
    color=models.ForeignKey("Color",on_delete=models.CASCADE)
    price=models.PositiveBigIntegerField()
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='uploads/products/')
    
    def __str__(self):
        return self.product.name

store/views.py
from django.urls import reverse
from django.conf import settings
import json 
from django.http import HttpResponse,JsonResponse
from django.shortcuts import render,redirect,HttpResponseRedirect
from django.contrib.auth.hashers import make_password,check_password
from django.http import HttpResponse
from django.views import View
from .models import Product,Category,Customer,Order,Brand,Size,ProductAttribute,Color
from store.middlewares.auth import auth_middleware
from django.template.loader import render_to_string
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt


class Index(View):
    
    def get(self,request):
        cart=request.session.get('cart')
        if not cart:
            request.session['cart']={}
        product=None
        
        name=request.session.get('customer_name')
        categories=Category.get_all__category()
        categoryid=request.GET.get('category')
        brandlist=Brand.get_all__brand()
        brandid=request.GET.get('brand')
        if categoryid:
                product=Product.get_all__products_by_ID(categoryid)
        elif brandid:
            product=Product.get_all__products_by_brandID(brandid)
        else:
            product=Product.get_all__products()
        context = {
            "product": product,
            "category":categories,
            "brandlist":brandlist,
            "name":name,
            
        }
        return render(request,'index.html',context)
   
def Brand_list(request):
    brands=Brand.get_all__brand()
    data = {
            "data":brands,
        }
    return render(request,'brand.html',data)

def category(request):
    categories=Category.get_all__category()
    data = {
            "data":categories,
        }
    return render(request,'category.html',data)

class Signup(View):
    def get(self,request):
        return render(request,'registration/signup.html')

    def post(self,request):
        data= request.POST
        first_name=data.get('firstname')
        last_name=data.get('lastname')
        email=data.get('email')
        password=data.get('password')
        phone=data.get('phone')
        #validation
        value={
            'first_name':first_name,
            'last_name':last_name,
            'email':email,
            'phone':phone
        }
        error_message=None
        customer=Customer(
                first_name=first_name,
                last_name=last_name,
                email=email,
                phone=phone,
                password=password,
            )
        error_message=self.ValidateCustomer(customer)
     #saving
        if not error_message:
            customer.password=make_password(customer.password)
            customer.register()
            return redirect('login')
        else:
            context={
                'error':error_message,
                'values':value
            }
            return render(request,'registration/signup.html',context)

    def ValidateCustomer(self,customer):
        error_message=None
        if(not customer.first_name):
            error_message="First name required!!!"
        elif len(customer.first_name)<4:
            error_message="First name must be 4 character long or more"
        elif not customer.last_name:
            error_message="Last name required!!!"
        elif len(customer.last_name)<4:
            error_message="Last name must be 4 character long or more"
        elif not customer.phone:
            error_message="Phone Number required!!!"
        elif len(customer.phone)<10:
            error_message="Phone Number must be 10 character long"
        elif len(customer.email)<5:
            error_message="Email must be 5 character long"
        elif len(customer.password)<6:
            error_message="Password must be 6 character long"
        elif customer.isExists():
            error_message="Email Already Registered"
        return error_message

class Login(View):
    return_url=None
    def get(self,request):
        Login.return_url=request.GET.get('return_url')
        return render(request,'registration/login.html')

    def post(self,request):
        email=request.POST.get('email')
        password=request.POST.get('password')
        customer=Customer.get_customer_by_email(email)
        error_message=None
        if customer:
            flag=check_password(password,customer.password)
            if flag:
                request.session['customer']=customer.id 
                request.session['customer_name']=customer.first_name
                if Login.return_url:
                    return HttpResponseRedirect(Login.return_url)
                else:
                    Login.return_url=None
                    return redirect('home')
            else:
                error_message='Email Or Password Invalid!!!'
        else:
            error_message='Email Or Password Invalid!!!'

        return render(request,'registration/login.html',{'error':error_message})

def logout(request):
    request.session.clear()
    return redirect('login')

def search(request):
    q=request.GET['q']
    data=Product.objects.filter(name__icontains=q)   
    return render(request,'search.html',{'data':data})   

def product_detail(request,id):
    
    product=Product.objects.get(id=id)
    colors=ProductAttribute.objects.filter(product=product).values('color__name','color__id','color__color_code').distinct()
    sizes=ProductAttribute.objects.filter(product=product).values('size__name','size__id','color__id','price').distinct()
    context={
        'product':product,
        'colors':colors,
        'sizes':sizes
    }
    return render(request,'product-detail.html',context)

def filter_data(request):
	colors=request.GET.getlist('color[]')
	categories=request.GET.getlist('category[]')
	brands=request.GET.getlist('brand[]')
	
	allProducts=Product.objects.all().order_by('-id').distinct()
    
	if len(colors)>0:
		allProducts=allProducts.filter(productattribute__color__id__in=colors).distinct()
                       
	if len(categories)>0:
		allProducts=allProducts.filter(category__id__in=categories).distinct()
	if len(brands)>0:
		allProducts=allProducts.filter(brand__id__in=brands).distinct()
	t=render_to_string('ajax/product-list.html',{'product':allProducts})
	return JsonResponse({'data':t}) 

def add_to_cart(request):
    cart_p={}
    cart_p[str(request.GET['id'])]={
        'image':request.GET['image'],
        'name':request.GET['name'],
        'price':request.GET['price'],
        'qty':request.GET['qty'],}    
    if 'cartdata' in request.session:
        if str(request.GET['id']) in request.session['cartdata']:
            cart_data=request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty']=int(cart_p[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cartdata']=cart_data
        else:
            cart_data=request.session['cartdata']
            cart_data.update(cart_p)
            request.session['cartdata']=cart_data

    else:
        request.session['cartdata']=cart_p 
    
    return JsonResponse({'data':request.session['cartdata'],'totalitems':len(request.session['cartdata'])}) 
                
def cart_list(request):
    total_amt=0
    if 'cartdata' in request.session:
        for p_id,item in request.session['cartdata'].items():
            total_amt+=int(item['qty'])*float(item['price'])
        return render(request,'cart.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
    else:
        return render(request,'cart.html',{'cart_data':'','totalitems':0,'total_amt':total_amt})
               
def update_cart_item(request):
    p_id=str(request.GET['id'])
    p_qty=request.GET['qty']

    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data=request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty']=p_qty
            request.session['cartdata']=cart_data
    total_amt=0
    for p_id,item in request.session['cartdata'].items():
        total_amt+=int(item['qty'])*float(item['price'])
    t=render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
    return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

def delete_cart_item(request):
    p_id=str(request.GET['id'])
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data=request.session['cartdata']
            del request.session['cartdata'][p_id]
            request.session['cartdata']=cart_data
    total_amt=0
    for p_id,item in request.session['cartdata'].items():
        total_amt+=int(item['qty'])*float(item['price'])
    t=render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
    return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

@auth_middleware
def checkout(request):
    order_id='123'
    host=request.get_host()
    paypal_dict={
        'business':settings.PAYPAL_RECEIVER_EMAIL,
        'amount':'123',
        'item_name':'Item Name',
        'invoice':'INV-123',
        'currency_code':'USD',
        'return_url':'http://{}{}'.format(host,reverse('payment_done')),
        'cancel_return':'http://{}{}'.format(host,reverse('payment_cancelled')),

    }
    form = PayPalPaymentsForm(initial=paypal_dict)
    total_amt=0
    if 'cartdata' in request.session:
        for p_id,item in request.session['cartdata'].items():
            total_amt+=int(item['qty'])*float(item['price'])
        return render(request,'checkout.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt,'form':form}) 


@csrf_exempt
def payment_done(request):

store/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>E-SHOP</title>
    <link rel="stylesheet" type="text/css" href="{% static 'ustom.css'%}"/>
    <script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'custom.js' %}"></script>

  </head>
  <body>

  <!-- navbar -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">E-Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Store <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link pb-1" href="/brand">Brand <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link pb-1" href="/category">Category <span class="sr-only">(current)</span></a>
      </li>
      <form class="form-inline my-2 my-lg-0">
    </form>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="/search">
      <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
      <ul class="navbar-nav my-2 my-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="/cart"><i class="fa fa-shopping-cart"></i>Cart 
            <span class="cart-list">{{request.session.cartdata|length}}</span>
            <span class="sr-only">(current)</span></a>
        </li>
      {% if request.session.customer %}
        <li class="nav-item active">
          <a class="nav-link" href="/order">Orders <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/logout">Logout <span class="sr-only">(current)</span></a>
        </li>
      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="/login">Login <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/signup">Signup <span class="sr-only">(current)</span></a>
        </li>
      {%endif%}
    
    </ul>

 
  </div>
</nav>

{% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
    src="https://code.jquery.com/jquery-3.6.1.min.js"
    integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
   

store/templates/brand.html
{% extends 'base.html'%}


  <!-- body -->
{% block content %}

{% load custom_filters %}

<div class="container-fluid mt-3">
    <h3 class="pb-1 bottom-border">BRAND</h3>
<div class="row">

  <!--all products-->

  <div id="brand" class="col-lg-9 mx-auto">
    <div class="row mx-auto" >
      {% for brand in data %} 
          <div class="card mx-auto mb-3" id={{brand.id}} style="width: 18rem;">
              <img class="card-img-top mt-2 mb-2 " src="/{{brand.image}}" alt="Card image cap">
              <div class="card-body ">
                <a href="/?brand={{brand.id}}" class="list-group-item list-group-item-action ">{{brand.name}}</a>
              </div>
          </div>
          
      {% endfor %}
  </div>
  </div>
</div>
</div>
{% endblock %}   

store/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load custom_filters %}
<main class="container my-4" id="cartList">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Cart ({{totalitems}})</h3>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Product</th>
				<th>Qty</th>
				<th>Price</th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			{% for product_id,item in cart_data.items %}
			<tr>
				<td>
					<img src="/{{item.image}}" width="50" />
					<p><a href="/product/{{product_id}}">{{item.name}}</a></p>
				</td>
				<td>
					<input type="number" class="product-qty-{{product_id}}" value="{{item.qty}}" style="vertical-align: bottom;" />
					<button class="btn btn-sm btn-primary update-item" data-item="{{product_id}}"><i class="fa fa-sync"></i></button>
					<button class="btn btn-sm btn-danger delete-item" data-item="{{product_id}}"><i class="fa fa-trash"></i></button>
				</td>
				<td> {{item.price|currency}}</td>
				<td>₹ {% widthratio item.price 1 item.qty %}</td>
			</tr>
			{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<td colspan="2"></td>
				<th>Total</th>
				<th> {{total_amt|currency}}</th>
			</tr>
			{% if totalitems %}
			<tr>
				<td colspan="4" align="right">
					<a href="{% url 'checkout' %}" class="btn btn-dark btn-sm">Checkout <i class="fa fa-long-arrow-alt-right"></i></a>
				</td>
			</tr>
			{% endif %}
		</tfoot>
	</table>
</main>
{% endblock %}

store/templates/category.html
{% extends 'base.html'%}


  <!-- body -->
{% block content %}

{% load custom_filters %}

<div class="container-fluid mt-3">
    <h3 class="pb-1 bottom-border">CATEGORIES</h3>
<div class="row">

  <!--all products-->

  <div id="brand" class="col-lg-9 mx-auto">
    <div class="row mx-auto" >
      {% for cat in data %} 
          <div class="card mx-auto mb-3" id={{cat.id}} style="width: 18rem;">
              <img class="card-img-top mt-2 mb-2 " src="/{{cat.image}}" alt="Card image cap">
              <div class="card-body ">
                <a href="/?category={{cat.id}}" class="list-group-item list-group-item-action ">{{cat.name}}</a>
              </div>
          </div>
      {% endfor %}
  </div>
  </div>
</div>
</div>
{% endblock %}   

store/templates/index.html
{% extends 'base.html'%}


  <!-- body -->
{% block content %}

{% load custom_filters %}
{% load static %}

<div class="container-fluid mt-3">
<div class="row">
  <!--filter-->
  <div class="col-lg-3 mx-auto">
    
  {%include 'filters.html'%}  
  </div> 
</div>
  
</div>

  <!--all products-->
  <div id="products" class="col-lg-9 mx-auto">
    <div class="row mx-auto" id="filteredProducts">
      <p class="ajaxLoader">loading...</p>
      {% for product in product %} 
          <div class="card mx-auto mb-3" id={{product.id}} style="width: 18rem;">
              <img class="card-img-top" src="/{{product.productattribute_set.first.image}}" alt="Card image cap">
              <div class="card-body">
                  <p class="card-title">{{product.name}}</p>
                  <p class="card-text"><strong>{{product.productattribute_set.first.price|currency}}</strong></p>
                  <p class="nav-link pb-1"><a href="/product/{{product.id}}">View Product</a></p>
              </div>

            <div class="card-footer p-0 no-gutters">
             
                <div class="row no-gutters" >
                  
                  
                  
                </div>
              
            </div>
          </div>
      {% endfor %}
  </div>
  </div>
</div>

</div>
{% endblock %}   

store/templates/payment-fail.html
{% extends 'base.html'%}
{%load static %}
{% block content %}
<main class="container my-4" id="cartlist">
    <p>Payment Failed</p>
</main>
{% endblock%}

store/templates/payment-success.html
{% extends 'base.html'%}
{%load static %}
{% block content %}
<main class="container my-4" id="cartlist">
    <p>Payment Success</p>
</main>
{% endblock%}

store/templates/product-detail.html
{% extends 'base.html'%}

  <!-- body -->
{% block content %}

{% load custom_filters %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">{{product.name}}</h3>
	<div class="row">
		<!-- Images -->
		<div class="col-md-4">
			<img id="zoom_01" src="/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{data.name}}">
		</div>
		<div class="col-md-8">
			<p>{{product.detail}}</p>
			<hr/>
			<table class="table table-bordered">
				<tr>
					<th>Colors</th>
					<td>
						{% for color in colors %}
							<button class="btn btn-lg choose-color" data-color="{{color.color__id}}" style="background-color:{{color.color__color_code}}"></button>
						{% endfor %}
					</td>
				</tr>
				<tr>
					<th>Sizes</th>
					<td>
						{% for size in sizes %}
						<button data-price="{{size.price}}" class="btn btn-outline-secondary btn-sm choose-size color{{size.color__id}}">{{size.size__name}}</button>
						{% endfor %}
					</td>
				</tr>
				<tr>
					<th>Price</th>
					
					<th> ₹ <span class="product-price"> {{product.productattribute_set.first.price|currency}}</span></th>
				</tr>
			</table>
			<hr/>
			<div class="input-group my-3" style="width:30%;">
				<input type="number" value="1" class="form-control" id="productQty"/>
				<div class="input-group-append">
					<input type="hidden" class="product-image" value="{{product.productattribute_set.first.image}}" />
					<input type="hidden" class="product-id" value="{{product.id}}" />
					<input type="hidden" class="product-name" value="{{product.name}}" />
				  <button class="btn btn-primary btn-sm add-to-cart" data-index="{{product.id}}" type="button" id="addToCartBtn"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
				</div>
			  </div>
			  <div class="row">
				<div class="col-md-6">
					<h3 class="my-3">Detail</h3>
					<!-- Detail -->
					<table class="table table-bordered">
						<tr>
							<th>Brand</th>
							<td><a href="/?brand={{product.brand.id}}">{{product.brand.name}}</a></td>
						</tr>
						<tr>
							<th>Category</th>
							<td><a href="/?category={{product.category.id}}">{{product.category.name}}</a></td>
						</tr>
						<tr>
							<th>Specification</th>
							<td>{{product.specs}}</td>
						</tr>
					</table>
				</div>
		  </div>
	  </div>
	  <hr />
  {% endblock %}

store/templates/search.html
{% extends 'base.html'%}


  <!-- body -->
{% block content %}

{% load custom_filters %}

<div class="container-fluid mt-3">
<div class="row">
  <!--filter-->
  <div class="col-lg-3 mx-auto">

  <!--all products-->
  <h3 class="my-4 border-bottom pb-1"><span class="text-muted">search result for</span> {{request.GET.q}}</h3>
  <div id="products" class="col-lg-9 mx-auto">
    <div class="row mx-auto" >
      {% for product in data %} 
          <div class="card mx-auto mb-3" id={{product.id}} style="width: 18rem;">
              <img class="card-img-top" src="{{product.productattribute_set.first.image.url}}" alt="Card image cap">
              <div class="card-body">
                  <p class="card-title">{{product.name}}</p>
                  <p class="card-text"><strong>{{product.productattribute_set.first.price|currency}}</strong></p>
              </div>
            <div class="card-footer p-0 no-gutters">
              {% if product|is_in_cart:request.session.cart %}
                <div class="row no-gutters" >
                  <form action="/#{{product.id}}" method="POST" class="-col-2">
                    {% csrf_token %}
                    <input hidden type="text" name="product" value='{{product.id}}'>
                    <input hidden type="text" name="remove" value='True'>
                    <input type="submit" value="-"  class="float-right btn btn-secondary border form-control
                    ">
                  </form>
                  <div class="text-center col">{{product|cart_quantity:request.session.cart}} in cart</div>
                  <form action="/#{{product.id}}" method="POST" class="-col-2 ">
                    {% csrf_token %}
                    <input hidden type="text" name="product" value='{{product.id}}'>
                    <input type="submit" value="+"  class="float-right btn btn-secondary border form-control ">
                  </form>
                </div>
              {% else %}
                <form action="/#{{product.id}}" method="POST" class="btn-block">
                  {% csrf_token %}
                  <input hidden type="text" name="product" value='{{product.id}}'>
                  <input href="#" type="submit" value="Add To Cart"  class="float-right btn btn-light border form-control">
                </form>
              {% endif %}
            </div>
          </div>
      {% endfor %}
  </div>
  </div>
</div>

</div>
{% endblock %}   